/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#0053db",
        "on-primary": "#ffffff",
        "outline-variant": "#c3c6d7",
        "tertiary": "#824500",
        "on-tertiary-fixed-variant": "#6e3900",
        "secondary-fixed": "#85f8c4",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container": "#eaedff",
        "tertiary-fixed-dim": "#ffb77d",
        "surface": "#faf8ff",
        "on-surface": "#131b2e",
        "primary-fixed-dim": "#b4c5ff",
        "surface-container-low": "#f2f3ff",
        "secondary": "#006c4a",
        "on-tertiary-fixed": "#2f1500",
        "surface-variant": "#dae2fd",
        "inverse-surface": "#283044",
        "background": "#faf8ff",
        "on-background": "#131b2e",
        "on-secondary-fixed": "#002114",
        "on-surface-variant": "#434655",
        "primary-fixed": "#dbe1ff",
        "on-primary-fixed": "#00174b",
        "secondary-container": "#82f5c1",
        "on-secondary-fixed-variant": "#005137",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00714e",
        "on-tertiary-container": "#ffede1",
        "on-error-container": "#93000a",
        "surface-dim": "#d2d9f4",
        "primary-container": "#2563eb",
        "surface-bright": "#faf8ff",
        "inverse-primary": "#b4c5ff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#68dba9",
        "tertiary-container": "#a65900",
        "surface-container-highest": "#dae2fd",
        "inverse-on-surface": "#eef0ff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "surface-container-high": "#e2e7ff",
        "tertiary-fixed": "#ffdcc3",
        "primary": "#004ac6",
        "on-primary-container": "#eeefff",
        "outline": "#737686"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-lg": "1.25rem",
        "space-xs": "0.25rem",
        "gutter": "1rem",
        "space-xl": "1.75rem",
        "space-md": "0.75rem",
        "margin": "1.5rem",
        "space-sm": "0.375rem"
      },
      fontFamily: {
        "data-mono": ["JetBrains Mono", "monospace"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "data-mono-lg": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "data-mono": ["12px", { lineHeight: "16px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "data-mono-lg": ["14px", { lineHeight: "20px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.005em", fontWeight: "400" }],
        "body-lg": ["15px", { lineHeight: "22px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }]
      }
    }
  },
  plugins: [],
}
