import React, { useState, useEffect } from 'react';
import { useAuth, type ReceiptSettings } from '../contexts/AuthContext';
import { api } from '../lib/api';

export interface ReceiptData {
  receiptNumber: string;
  studentName: string;
  registerNo: string;
  course?: string;
  department?: string;
  amount: number;
  paymentMethod: string;
  transactionReference?: string;
  date?: string | Date;
  balanceRemaining?: number;
  totalFee?: number;
  notes?: string;
  logoUrl?: string;
  institutionName?: string;
  whatsappNumber?: string;
}

export function cleanWhatsAppNumber(phone?: string): string {
  if (!phone) return '';
  let digits = phone.replace(/\D/g, '');
  if (!digits) return '';
  if (digits.length === 10) {
    digits = `91${digits}`;
  } else if (digits.length === 11 && digits.startsWith('0')) {
    digits = `91${digits.slice(1)}`;
  }
  return digits;
}

export function generateWhatsAppReceiptText(receipt: ReceiptData): string {
  const instName = receipt.institutionName || 'ALPHAXYNC ACADEMIC OPERATIONS';
  const dateStr = receipt.date
    ? new Date(receipt.date).toLocaleDateString('en-IN', {
        day: '2-digit',
        month: 'short',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      })
    : new Date().toLocaleDateString('en-IN');

  const bal = Number(receipt.balanceRemaining ?? 0);
  const statusStr = bal === 0 ? '✅ FULLY SETTLED / NIL DUES' : `⚠️ PARTIAL PAYMENT (Due: ₹${bal.toLocaleString('en-IN')})`;

  return `🏛️ *${instName.toUpperCase()}*
📄 *OFFICIAL FEE PAYMENT RECEIPT*
━━━━━━━━━━━━━━━━━━━━
🧾 *Receipt No:* ${receipt.receiptNumber}
📅 *Date:* ${dateStr}
👤 *Student:* ${receipt.studentName}
🆔 *Register No:* ${receipt.registerNo}
🎓 *Course / Dept:* ${receipt.course || receipt.department || 'General'}
💳 *Payment Mode:* ${receipt.paymentMethod || 'UPI / Online'}
🔢 *Txn Reference:* ${receipt.transactionReference || 'VERIFIED'}
━━━━━━━━━━━━━━━━━━━━
💰 *AMOUNT PAID:* ₹${Number(receipt.amount).toLocaleString('en-IN')}
📊 *Status:* ${statusStr}
${bal > 0 ? `⏳ *Balance Due:* ₹${bal.toLocaleString('en-IN')}\n` : '🏆 *Clearance:* Fee dues 100% cleared for this term.\n'}━━━━━━━━━━━━━━━━━━━━
_Verified digital e-receipt generated by CampusFlow._`;
}

export function getWhatsAppReceiptUrl(receipt: ReceiptData): string {
  const text = generateWhatsAppReceiptText(receipt);
  const cleanPhone = cleanWhatsAppNumber(receipt.whatsappNumber);
  if (cleanPhone) {
    return `https://wa.me/${cleanPhone}?text=${encodeURIComponent(text)}`;
  }
  return `https://wa.me/?text=${encodeURIComponent(text)}`;
}

export const DEFAULT_RECEIPT_SETTINGS: ReceiptSettings = {
  headerTitleSize: 20,
  headerTitleColor: '#111827',
  headerSubtitleText: 'Institutional Operations & Accounts Department',
  headerSubtitleSize: 12,
  headerSubtitleColor: '#4b5563',
  badgeText: 'FEE COLLECTION VOUCHER / OFFICIAL RECEIPT',
  headerLogoSize: 44,
  headerLogoPosition: 'inline',
  showWatermark: true,
  watermarkCustomUrl: '',
  watermarkSize: 280,
  watermarkOpacity: 0.10,
  watermarkRotation: -12,
  watermarkGrayscale: true,
  bodyFontSize: 12,
  primaryColor: '#1e40af',
  textColor: '#1f2937',
  secondaryTextColor: '#6b7280',
  cardBgColor: '#ffffff',
  cardBgOpacity: 1.0,
  cardBorderColor: '#e5e7eb',
  sectionBgColor: '#f8fafc',
  tableBorderColor: '#e2e8f0',
  footerNotes: '• Computer generated official receipt.\n• Verified against institutional ledger.',
  signatoryLabel: 'Authorized Signatory',
  showSignatoryLine: true
};

export function hexToRgba(hex?: string, opacity: number = 1): string {
  if (!hex) return `rgba(255, 255, 255, ${opacity})`;
  let clean = hex.replace('#', '').trim();
  if (clean.length === 3) {
    clean = clean.split('').map((c) => c + c).join('');
  }
  const r = parseInt(clean.substring(0, 2), 16) || 255;
  const g = parseInt(clean.substring(2, 4), 16) || 255;
  const b = parseInt(clean.substring(4, 6), 16) || 255;
  const safeOpacity = Math.max(0, Math.min(1, opacity));
  return `rgba(${r}, ${g}, ${b}, ${safeOpacity})`;
}

export interface ReceiptPaperProps {
  receipt: ReceiptData;
  customSettings?: ReceiptSettings;
  className?: string;
}

export const ReceiptPaper: React.FC<ReceiptPaperProps> = ({ receipt, customSettings, className = '' }) => {
  const { institution } = useAuth();
  const [fetchedInst, setFetchedInst] = useState<{ name?: string; logoUrl?: string; receiptSettings?: ReceiptSettings } | null>(null);

  useEffect(() => {
    if (!receipt?.logoUrl && !institution?.logoUrl) {
      api.getSettings().then((res: any) => {
        if (res?.institution) {
          setFetchedInst({
            name: res.institution.name,
            logoUrl: res.institution.logoUrl,
            receiptSettings: res.institution.receiptSettings
          });
        }
      }).catch(() => {});
    }
  }, [receipt?.logoUrl, institution?.logoUrl]);

  const activeSettings: ReceiptSettings = {
    ...DEFAULT_RECEIPT_SETTINGS,
    ...(institution?.receiptSettings || {}),
    ...(fetchedInst?.receiptSettings || {}),
    ...(customSettings || {})
  };

  const institutionTitle = receipt.institutionName || institution?.name || fetchedInst?.name || "Official Campus Receipt";
  const logoUrl = receipt.logoUrl || institution?.logoUrl || fetchedInst?.logoUrl;
  const watermarkUrl = activeSettings.watermarkCustomUrl || logoUrl;

  const formattedDate = receipt.date
    ? new Date(receipt.date).toLocaleString('en-IN', {
        day: '2-digit',
        month: 'short',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      })
    : new Date().toLocaleString('en-IN', {
        day: '2-digit',
        month: 'short',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      });

  const cardBg = hexToRgba(activeSettings.cardBgColor || '#ffffff', activeSettings.cardBgOpacity ?? 1.0);
  const isTranslucent = (activeSettings.cardBgOpacity ?? 1.0) < 1.0;

  return (
    <div
      id="printable-receipt"
      className={`relative p-6 select-none font-sans overflow-hidden border rounded-xl shadow-sm transition-all ${className}`}
      style={{
        fontSize: `${activeSettings.bodyFontSize || 12}px`,
        color: activeSettings.textColor || '#1f2937',
        backgroundColor: cardBg,
        borderColor: activeSettings.cardBorderColor || '#e5e7eb',
        backdropFilter: isTranslucent ? 'blur(12px)' : undefined,
        WebkitBackdropFilter: isTranslucent ? 'blur(12px)' : undefined,
        minHeight: '480px'
      }}
    >
      {/* Center Watermark Emblem (Anti-forgery official seal) */}
      {activeSettings.showWatermark && (
        <div className="absolute inset-0 flex items-center justify-center pointer-events-none select-none z-0 overflow-hidden">
          {watermarkUrl ? (
            <img
              src={watermarkUrl}
              alt="Watermark"
              style={{
                width: `${activeSettings.watermarkSize}px`,
                height: `${activeSettings.watermarkSize}px`,
                opacity: activeSettings.watermarkOpacity,
                transform: `rotate(${activeSettings.watermarkRotation}deg)`,
                filter: activeSettings.watermarkGrayscale ? 'grayscale(100%) contrast(125%)' : 'contrast(110%)'
              }}
              className="object-contain transition-all"
            />
          ) : (
            <div
              style={{
                width: `${activeSettings.watermarkSize}px`,
                height: `${activeSettings.watermarkSize}px`,
                opacity: activeSettings.watermarkOpacity,
                transform: `rotate(${activeSettings.watermarkRotation}deg)`
              }}
              className="rounded-full border-8 border-gray-900 flex flex-col items-center justify-center transition-all"
            >
              <span className="font-serif font-black text-3xl tracking-widest text-gray-900">CAMPUS</span>
              <span className="text-[10px] font-bold tracking-widest uppercase text-gray-900 mt-1">OFFICIAL SEAL</span>
            </div>
          )}
        </div>
      )}

      <div className="relative z-10">
        {/* Institution Header */}
        <div
          className="text-center pb-3 mb-4"
          style={{ borderBottom: `2px solid ${activeSettings.primaryColor || '#111827'}` }}
        >
          {activeSettings.headerLogoPosition === 'stacked' ? (
            <div className="flex flex-col items-center justify-center gap-1.5 mb-1.5">
              {logoUrl ? (
                <img
                  src={logoUrl}
                  alt="Campus Logo"
                  style={{
                    width: `${activeSettings.headerLogoSize}px`,
                    height: `${activeSettings.headerLogoSize}px`
                  }}
                  className="object-contain rounded shadow-sm bg-white p-0.5 border border-gray-200 shrink-0"
                />
              ) : (
                <span
                  style={{
                    width: `${activeSettings.headerLogoSize}px`,
                    height: `${activeSettings.headerLogoSize}px`
                  }}
                  className="rounded bg-blue-700 text-white font-bold flex items-center justify-center text-sm shadow-sm shrink-0"
                >
                  CF
                </span>
              )}
              <h2
                className="font-bold uppercase tracking-wide leading-tight px-2"
                style={{
                  fontSize: `${activeSettings.headerTitleSize}px`,
                  color: activeSettings.headerTitleColor
                }}
              >
                {institutionTitle}
              </h2>
            </div>
          ) : (
            <div className="flex items-center justify-center gap-2.5 mb-1.5">
              {logoUrl ? (
                <img
                  src={logoUrl}
                  alt="Campus Logo"
                  style={{
                    width: `${activeSettings.headerLogoSize}px`,
                    height: `${activeSettings.headerLogoSize}px`
                  }}
                  className="object-contain rounded shadow-sm bg-white p-0.5 border border-gray-200 shrink-0"
                />
              ) : (
                <span
                  style={{
                    width: `${activeSettings.headerLogoSize}px`,
                    height: `${activeSettings.headerLogoSize}px`
                  }}
                  className="rounded bg-blue-700 text-white font-bold flex items-center justify-center text-sm shadow-sm shrink-0"
                >
                  CF
                </span>
              )}
              <h2
                className="font-bold uppercase tracking-wide leading-tight"
                style={{
                  fontSize: `${activeSettings.headerTitleSize}px`,
                  color: activeSettings.headerTitleColor
                }}
              >
                {institutionTitle}
              </h2>
            </div>
          )}

          {activeSettings.headerSubtitleText && (
            <p
              style={{
                fontSize: `${activeSettings.headerSubtitleSize}px`,
                color: activeSettings.headerSubtitleColor
              }}
              className="mt-0.5 font-medium"
            >
              {activeSettings.headerSubtitleText}
            </p>
          )}

          {activeSettings.badgeText && (
            <div
              className="inline-block mt-1 px-3 py-0.5 rounded bg-gray-50 border text-[11px] font-mono font-bold tracking-widest uppercase shadow-2xs"
              style={{ borderColor: activeSettings.primaryColor }}
            >
              {activeSettings.badgeText}
            </div>
          )}
        </div>

        {/* Receipt Top Info */}
        <div
          className="flex justify-between items-center text-xs pb-2 mb-3 border-b"
          style={{ borderColor: activeSettings.tableBorderColor || '#e5e7eb' }}
        >
          <div>
            <span style={{ color: activeSettings.secondaryTextColor || '#6b7280' }}>Receipt No: </span>
            <span
              className="font-mono font-bold text-sm"
              style={{ color: activeSettings.primaryColor || '#1e40af' }}
            >
              {receipt.receiptNumber}
            </span>
          </div>
          <div>
            <span style={{ color: activeSettings.secondaryTextColor || '#6b7280' }}>Date: </span>
            <span
              className="font-mono font-semibold"
              style={{ color: activeSettings.textColor || '#1f2937' }}
            >
              {formattedDate}
            </span>
          </div>
        </div>

        {/* Student Details Grid */}
        <div
          className="rounded p-3 mb-4 border grid grid-cols-2 gap-2 text-xs transition-colors"
          style={{
            backgroundColor: activeSettings.sectionBgColor || '#f8fafc',
            borderColor: activeSettings.tableBorderColor || '#e5e7eb'
          }}
        >
          <div>
            <span
              className="block text-[10px] uppercase tracking-wider font-medium"
              style={{ color: activeSettings.secondaryTextColor || '#6b7280' }}
            >
              Student Name
            </span>
            <span
              className="font-bold text-sm"
              style={{ color: activeSettings.textColor || '#111827' }}
            >
              {receipt.studentName}
            </span>
          </div>
          <div>
            <span
              className="block text-[10px] uppercase tracking-wider font-medium"
              style={{ color: activeSettings.secondaryTextColor || '#6b7280' }}
            >
              Register / Roll No
            </span>
            <span
              className="font-mono font-semibold text-sm"
              style={{ color: activeSettings.textColor || '#111827' }}
            >
              {receipt.registerNo}
            </span>
          </div>
          <div>
            <span
              className="block text-[10px] uppercase tracking-wider font-medium"
              style={{ color: activeSettings.secondaryTextColor || '#6b7280' }}
            >
              Course / Degree
            </span>
            <span
              className="font-medium"
              style={{ color: activeSettings.textColor || '#374151' }}
            >
              {receipt.course || 'BCA / Engineering'}
            </span>
          </div>
          <div>
            <span
              className="block text-[10px] uppercase tracking-wider font-medium"
              style={{ color: activeSettings.secondaryTextColor || '#6b7280' }}
            >
              Department
            </span>
            <span
              className="font-medium"
              style={{ color: activeSettings.textColor || '#374151' }}
            >
              {receipt.department || 'General'}
            </span>
          </div>
        </div>

        {/* Payment Details Table */}
        <table
          className="w-full text-xs border-collapse border mb-4 transition-colors"
          style={{ borderColor: activeSettings.tableBorderColor || '#e2e8f0' }}
        >
          <thead>
            <tr
              style={{
                backgroundColor: activeSettings.sectionBgColor || '#f1f5f9',
                color: activeSettings.secondaryTextColor || '#475569'
              }}
            >
              <th
                className="border p-2 text-left font-semibold"
                style={{ borderColor: activeSettings.tableBorderColor || '#e2e8f0' }}
              >
                Description
              </th>
              <th
                className="border p-2 text-center font-semibold"
                style={{ borderColor: activeSettings.tableBorderColor || '#e2e8f0' }}
              >
                Payment Mode
              </th>
              <th
                className="border p-2 text-right font-semibold"
                style={{ borderColor: activeSettings.tableBorderColor || '#e2e8f0' }}
              >
                Amount Paid
              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td
                className="border p-2 font-medium"
                style={{
                  borderColor: activeSettings.tableBorderColor || '#e2e8f0',
                  color: activeSettings.textColor || '#1f2937'
                }}
              >
                Tuition Fee Installment
                {receipt.transactionReference && (
                  <span
                    className="block text-[10px] font-mono mt-0.5"
                    style={{ color: activeSettings.secondaryTextColor || '#6b7280' }}
                  >
                    Ref: {receipt.transactionReference}
                  </span>
                )}
              </td>
              <td
                className="border p-2 text-center font-sans font-semibold"
                style={{ borderColor: activeSettings.tableBorderColor || '#e2e8f0' }}
              >
                {receipt.paymentMethod === 'UPI' ? (
                  <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-purple-50 text-purple-700 font-semibold text-[11px] border border-purple-200 shadow-2xs">
                    <span>📱</span> UPI / QR (GPay/Paytm)
                  </span>
                ) : receipt.paymentMethod === 'CASH' ? (
                  <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-amber-50 text-amber-800 font-semibold text-[11px] border border-amber-200 shadow-2xs">
                    <span>🏢</span> On-Spot Counter Cash
                  </span>
                ) : receipt.paymentMethod === 'RAZORPAY' ? (
                  <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-blue-50 text-blue-700 font-semibold text-[11px] border border-blue-200 shadow-2xs">
                    <span>🌐</span> Online (Razorpay)
                  </span>
                ) : (
                  <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-gray-50 text-gray-700 font-semibold text-[11px] border border-gray-200 shadow-2xs">
                    <span>💳</span> {receipt.paymentMethod || 'CASH'}
                  </span>
                )}
              </td>
              <td
                className="border p-2 text-right font-mono font-bold text-emerald-700 text-sm"
                style={{ borderColor: activeSettings.tableBorderColor || '#e2e8f0' }}
              >
                ₹{Number(receipt.amount).toLocaleString('en-IN')}
              </td>
            </tr>
          </tbody>
          <tfoot>
            {receipt.balanceRemaining !== undefined && (
              <tr
                style={{
                  backgroundColor: activeSettings.sectionBgColor || '#f8fafc',
                  borderColor: activeSettings.tableBorderColor || '#e2e8f0'
                }}
              >
                <td
                  colSpan={2}
                  className="border p-2 text-right font-semibold"
                  style={{
                    borderColor: activeSettings.tableBorderColor || '#e2e8f0',
                    color: activeSettings.secondaryTextColor || '#4b5563'
                  }}
                >
                  Remaining Outstanding Balance:
                </td>
                <td
                  className="border p-2 text-right font-mono font-bold text-red-600"
                  style={{ borderColor: activeSettings.tableBorderColor || '#e2e8f0' }}
                >
                  ₹{Number(receipt.balanceRemaining).toLocaleString('en-IN')}
                </td>
              </tr>
            )}
          </tfoot>
        </table>

        {/* Dynamic Next Payment QR or Full Settlement Clearance */}
        {receipt.balanceRemaining !== undefined && receipt.balanceRemaining > 0 ? (
          <div
            className="mb-4 p-2.5 rounded border border-dashed flex items-center justify-between gap-3"
            style={{
              backgroundColor: activeSettings.sectionBgColor || '#f8fafc',
              borderColor: activeSettings.tableBorderColor || '#cbd5e1'
            }}
          >
            <div>
              <div
                className="flex items-center gap-1.5 text-[11px] font-bold"
                style={{ color: activeSettings.textColor || '#1e293b' }}
              >
                <span>📲</span>
                <span>Next Installment QR & Online Pay Link</span>
              </div>
              <p
                className="text-[10px] mt-0.5"
                style={{ color: activeSettings.secondaryTextColor || '#64748b' }}
              >
                Scan with any UPI app (GPay / PhonePe / Paytm) to pay remaining ₹{Number(receipt.balanceRemaining).toLocaleString('en-IN')}
              </p>
              <p
                className="text-[9px] font-mono mt-1 underline"
                style={{ color: activeSettings.primaryColor || '#2563eb' }}
              >
                http://xync.alphaprime.co.in/pay?reg={receipt.registerNo}
              </p>
            </div>
            <div className="w-16 h-16 bg-white p-1 rounded border border-slate-200 shrink-0 shadow-2xs">
              <img
                src={`https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=${encodeURIComponent(`upi://pay?pa=alphaxync@upi&pn=AlphaXync&am=${receipt.balanceRemaining}&cu=INR&tn=${receipt.registerNo}_BAL`)}`}
                alt="Next Payment QR"
                className="w-full h-full object-contain"
              />
            </div>
          </div>
        ) : receipt.balanceRemaining === 0 ? (
          <div className="mb-4 p-2 rounded bg-emerald-50 border border-emerald-300 flex items-center gap-2 text-emerald-800">
            <span className="text-base">🏆</span>
            <div className="text-[11px] font-semibold">
              Official Clearance: All prescribed fee dues for this term are 100% settled and cleared (Nil Balance).
            </div>
          </div>
        ) : null}

        {/* Footer & Signature */}
        <div
          className="flex justify-between items-end pt-4 mt-4 border-t text-xs"
          style={{ borderColor: activeSettings.tableBorderColor || '#e5e7eb' }}
        >
          <div
            className="text-[10px] leading-relaxed max-w-xs"
            style={{ color: activeSettings.secondaryTextColor || '#6b7280' }}
          >
            {activeSettings.footerNotes?.split('\n').map((line, idx) => (
              <p key={idx}>{line}</p>
            ))}
          </div>
          <div className="text-center">
            {activeSettings.showSignatoryLine && (
              <div
                className="w-32 border-b mb-1"
                style={{ borderColor: activeSettings.secondaryTextColor || '#9ca3af' }}
              ></div>
            )}
            <span
              className="text-[11px] font-semibold uppercase"
              style={{ color: activeSettings.secondaryTextColor || '#4b5563' }}
            >
              {activeSettings.signatoryLabel || 'Authorized Signatory'}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
};

interface ReceiptModalProps {
  receipt: ReceiptData | null;
  customSettings?: ReceiptSettings;
  onClose: () => void;
}

export const ReceiptModal: React.FC<ReceiptModalProps> = ({ receipt, customSettings, onClose }) => {
  if (!receipt) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleShareWhatsApp = () => {
    const url = getWhatsAppReceiptUrl(receipt);
    window.open(url, '_blank');
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-surface-container-lowest max-w-lg w-full rounded-xl shadow-2xl border border-outline-variant/30 overflow-hidden animate-fade-in">
        {/* Printable Card Area */}
        <ReceiptPaper receipt={receipt} customSettings={customSettings} />

        {/* Action Buttons (Excluded from Print) */}
        <div className="p-3 bg-surface-container-low border-t border-outline-variant/20 flex items-center justify-between gap-2 no-print">
          <div className="text-[11px] text-on-surface-variant flex items-center gap-1">
            <span className="material-symbols-outlined text-[15px] text-emerald-600">verified</span>
            <span>Ledger Authenticated</span>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleShareWhatsApp}
              className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded text-label-sm font-semibold flex items-center gap-1.5 shadow-sm transition-all"
              title="Share / Send Receipt to WhatsApp"
            >
              <span className="material-symbols-outlined text-[16px]">chat</span>
              <span>Send WhatsApp</span>
            </button>
            <button
              onClick={handlePrint}
              className="px-3.5 py-1.5 bg-primary hover:bg-primary/90 text-on-primary rounded text-label-sm font-semibold flex items-center gap-1.5 shadow-sm transition-all"
            >
              <span className="material-symbols-outlined text-[16px]">print</span>
              <span>Print / Save PDF</span>
            </button>
            <button
              onClick={onClose}
              className="px-3.5 py-1.5 bg-surface-container hover:bg-surface-container-high rounded text-label-sm text-on-surface transition-colors font-medium"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
